title: Faiq's blog
author: Faiq
email: faiq.fq@gmail.com
description: > # Time Series Forecasting
  Time Series Forecasting refers to the analysis and modelling of time-series data. It aids in predicting the future behavior of the market, which is useful for every business's decision-making. When working on an issue involving time series forecasting, you need to know how to select a forecasting model.

  The choice of the Time Series Forecasting model depends on the type of time series data you are working with. There are four types of time series data
  Stationary data
  Data with trends
  Seasonal data
  Cyclical series data


# social links
twitter_username: faiqlatheef
github_username:  Faiqlatheef

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
